[green_agent]
endpoint = "http://127.0.0.1:9020"
cmd = "python scenarios/captcha/captcha_judge.py --host 127.0.0.1 --port 9020"

[[participants]]
role = "captcha_solver"
endpoint = "http://127.0.0.1:9019"
cmd = "python scenarios/captcha/captcha_solver.py --host 127.0.0.1 --port 9019"

[config]
captcha_type = 'none'
puzzle_id = 'none'
captcha_host = "http://127.0.0.1"
captcha_port = 7861
captcha_app_path = "/Users/chenhaishuo/Documents/OpenCaptchaWorld/app2.py"
